### ISSUE TITLE
Should `isPriorityHigher` be unit tested?

### ISSUE THREAD

**Issue by kjetilkjeka** [UAVCAN/libcanard#101]
#100 brought it to our attention that there are no unit tests for `isPriorityHigher`.

This should be considered added.

**Comment by pavel-kirienko** [comment]
There is hardly anything that is unit-tested in this library.

**Comment by kjetilkjeka** [comment]
> There is hardly anything that is unit-tested in this library.

Feel free to close this one and add a more general issue regarding unit testing.

**Comment by pavel-kirienko** [comment]
Done.
