### ISSUE TITLE
Remove TAO

### ISSUE THREAD

**Issue by aasmune** [UAVCAN/libcanard#108]
The TAO (tail array optimization) logic needs to be removed.
See https://github.com/UAVCAN/libcanard/pull/106

**Comment by aasmune** [comment]
What need to be done in this issue @pavel-kirienko ?

**Comment by pavel-kirienko** [comment]
The DSDL compiler generates a bunch of tricky checks and branches that determine whether one of the variable-length arrays contained in the data type object should be encoded without being prefixed by its length field. All this needs to be removed, and every array should be encoded uniformly with its length field added always.

**Comment by aasmune** [comment]
So if I have understood it correctly: All dynamic arrays should be encoded with first the number of items, then all the values?

**Comment by pavel-kirienko** [comment]
Correct. Relevant context:

1. The old mailing list thread: https://groups.google.com/forum/#!topic/uavcan/guUjFsHk2Lo; search for the following text:
> I think this is the perfect occasion to share a revelation I had some time ago, a few years after announcing the first draft of the standard:
> TAO was a mistake.

2. https://github.com/UAVCAN/uavcan.github.io/issues/34

**Comment by aasmune** [comment]
Fixed in the current DSDL compiler. A proper solution will be to change to using pydsdlgen. Leaving the issue open awaiting the proper fix.
