### ISSUE TITLE
Missing constants in generated C files from DSDL

### ISSUE THREAD

**Issue by aasmune** [UAVCAN/libcanard#111]
I have noticed that the generated C file doesn't contain any constants if the source DSDL file consists only of constants, without any other fields.

E.g. the following file will be created as [Foo.1.0_no_constants.txt](https://github.com/UAVCAN/libcanard/files/3029658/Foo.1.0_no_constants.txt) (converted from .h to .txt to be able to upload to Github and renamed)
```
uint8 BAR = 123
```

However, the following file will be created as [Foo.1.0_with_constant.txt](https://github.com/UAVCAN/libcanard/files/3029673/Foo.1.0_with_constant.txt)
```
uint8 BAR = 123
uint8 placeholder
```
I haven't looked deeply on the output from pydsdl during parsing, but is this expected behavior, or a bug? It should also be mentioned that this is with an "old" version of pydsdl (before v0.4)
@pavel-kirienko

**Comment by pavel-kirienko** [comment]
> is this expected behavior, or a bug

It's a bug :beetle:

**Comment by pavel-kirienko** [comment]
This question reminds me that maybe the code generator should be based on https://github.com/UAVCAN/pydsdlgen

**Comment by aasmune** [comment]
> > is this expected behavior, or a bug
> 
> It's a bug 🐞

Do you know if its a bug with pydsdl or with the DSDL compiler in Libcanard?

> This question reminds me that maybe the code generator should be based on https://github.com/UAVCAN/pydsdlgen

I have also considered that we might should change to using that when it's ready.

**Comment by pavel-kirienko** [comment]
> I have also considered that we might should change to using that when it's ready.

Should we ask @thirtytwobits if it's ready yet?

**Comment by aasmune** [comment]
As I guess it will be some time before we change to using pydsdlgen I opened a PR, #113, with a fix for the current DSDL compiler.

**Comment by aasmune** [comment]
Fixed in #113
