### ISSUE TITLE
DSDL libcanard-compatible C source files or headers

### ISSUE THREAD

**Issue by williamyoung0** [UAVCAN/libcanard#123]
gnss_Fix.c

function uavcan_equipment_gnss_Fix_encode_internal
source->ned_velocity No conversion using canardConvertNativeFloatToFloat16 causes data parsing error

**Comment by pavel-kirienko** [comment]
@aasmune may I ask you to verify this, please?

**Comment by williamyoung0** [comment]
After I made changes to the code, the data was parsed normally. The following is the modification:
`	**tmp_float = canardConvertNativeFloatToFloat16(source->ned_velocity[c]);**
        canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
        offset += 16;`
