### ISSUE TITLE
How to process global time sync on libcanard

### ISSUE THREAD

**Issue by Cherish-forever** [UAVCAN/libcanard#128]
How can I use libcanard as time sync slave to update local timer?
Is there have any example?

**Comment by pavel-kirienko** [comment]
I am not aware of any, but it's not hard. The algorithm is described here: https://uavcan.org/Specification/6._Application_level_functions/#slave and implementation is available in libuavcan: https://github.com/UAVCAN/libuavcan/blob/master/libuavcan/include/uavcan/protocol/global_time_sync_slave.hpp
