### ISSUE TITLE
Abouta the uavcan v1.0

### ISSUE THREAD

**Issue by Linjieqiang** [UAVCAN/libcanard#136]
- When will the Uavcan v1.0 be released?  Can I use _branch uavcan-v1.0_ now?

**Comment by pavel-kirienko** [comment]
> When will the Uavcan v1.0 be released?

The official release is a huge thing and it is going to take some time. The v1 protocol itself is going to become available much sooner. Here are the blockers:

- https://github.com/UAVCAN/specification/issues/42
- https://forum.uavcan.org/t/big-endian-vs-little-endian-in-the-context-of-bit-level-encoding/428
- https://github.com/UAVCAN/libuavcan/projects/1
- https://github.com/UAVCAN/libcanard/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0
- https://github.com/UAVCAN/pyuavcan/milestone/1

Help with any of that would be appreciated.

> Can I use branch uavcan-v1.0 now?

Yes.
