### ISSUE TITLE
Pack Structures

### ISSUE THREAD

**Issue by masierra** [UAVCAN/libcanard#14]
Structure padding on different compilers can result in CanardRxState being too large. May need to pack them in a portable way.

**Comment by antoinealb** [comment]
yes we will need to use the uavcan standard for this. In the meantime something such as captn'proto or protobuf can be used if you dont require compatibility with libuavcan.

**Comment by pavel-kirienko** [comment]
No it's about `CanardRxState` being too large. The problem has no relation to the protocol itself.

**Comment by antoinealb** [comment]
Oh sorry, I answered too quickly, my bad... That's what I get for answering from my phone :wink:

I don't think there is a standard structure padding but supporting gcc and clang is probably enough, and they both accept `__attribute__`.

**Comment by pavel-kirienko** [comment]
Solution (continuing the Skype conversation):

```c
#define CANARD_RX_PAYLOAD_HEAD_SIZE (CANARD_MEM_BLOCK_SIZE - offsetof(CanardRxState, buffer_head))
#define CANARD_BUFFER_BLOCK_DATA_SIZE (CANARD_MEM_BLOCK_SIZE - offsetof(CanardBufferBlock, data))
```

(not tested)

**Comment by masierra** [comment]
I tested it on my linux machine and it seems to work. Push the change?

**Comment by pavel-kirienko** [comment]
Sure.
