### ISSUE TITLE
canardRxAccept fails with only one subcription

### ISSUE THREAD

**Issue by hugo-a-garcia** [UAVCAN/libcanard#154]
if only one subscription is available (eg hearbeat) then canardRxAccept() fails with 
 // No matching subscription.

but

it does not fail with 2 or more subscriptions

Can someone confirm this please.

**Comment by pavel-kirienko** [comment]
There is no perfect software but what you are describing seems unlikely. Can you please share any details?

**Comment by pat1** [comment]
If I am not wrong, some problems occurs if  CanardRxSubscription "object" is not on global scope or not static declared ...

**Comment by pavel-kirienko** [comment]
Where's the borrow checker when you need it?

Sounds like a lifetime management problem. Your subscription instances shall live at least until you call `canardRxUnsubscribe`. This is weakly hinted at by this statement but perhaps it's unclear:

https://github.com/UAVCAN/libcanard/blob/bd188fb82a79d5a3aba89b9e1504c9b85a015509/libcanard/canard.h#L265

**Comment by hugo-a-garcia** [comment]
Here is the code:

https://github.com/bluecorn/megaavr-can-multicast

If you comment out the dummy subscription (lines 60-66) then the "Hearbeat Recieved\n" (line 114) is not printed.

**Comment by pavel-kirienko** [comment]
Yeah, you have a lifetime management problem in your code. Make your subscriptions static. The docs have been clarified in https://github.com/UAVCAN/libcanard/pull/155, thanks for raising this.

**Comment by pavel-kirienko** [comment]
You have another problem of similar nature here, this is going to break terribly:

https://github.com/bluecorn/megaavr-can-multicast/blob/479ae485c2f7782fd9985a9605ea2a346235c245/megaavr-can-multicast.ino#L200-L207

**Comment by hugo-a-garcia** [comment]
Thank ypiu
