### ISSUE TITLE
Travis CI is no more, migrate to GitHub Actions

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/libcanard#172]
https://github.com/UAVCAN/libcanard/blob/master/.travis.yml

**Comment by pavel-kirienko** [comment]
Reopening because there are still configuration issues with CI.

- [ ] Test coverage measurement is not working, the reported coverage is 0%. This is probably because the sonar scanner configuration is incomplete -- it used to include more options:

https://github.com/UAVCAN/libcanard/blob/2a116170285fb47fcaae150ad21c2ccde0756a5f/.travis.yml#L33-L39

- [ ] SonarQube is analyzing irrelevant files, specifically `catch.hpp` (the unit testing framework) and CMake-generated C++ files (because the `sonar.sources` parameter is configured incorrectly):
   <img alt="image" src="https://user-images.githubusercontent.com/3298404/133212790-f444c621-8abb-4199-b5a3-7c8b16ea8e33.png">

Please avoid merging things without review, as it would help us avoid issues like this.

**Comment by coderkalyan** [comment]
> Please avoid merging things without review, as it would help us avoid issues like this.

Sorry, my intent was not to merge without review, but I found that the sonarcloud was not actually running anything on the PR branch since no code had changed. Now that I know it runs correctly, I will fix these issues and submit for review.

**Comment by pavel-kirienko** [comment]
Both of these deficiencies have been addressed by #181, thanks! One new issue is that Travis-CI integration is still enabled for some reason, as I wrote in a comment there, so I am going to keep this open.
