### ISSUE TITLE
build check error: narrowing conversion from 'int' to signed type 'int8_t' (aka 'signed char') is implementation-defined

### ISSUE THREAD

**Issue by Linjieqiang** [UAVCAN/libcanard#178]
![image](https://user-images.githubusercontent.com/10217966/129173122-b48a09db-90b5-417a-b866-a8511604e547.png)
![image](https://user-images.githubusercontent.com/10217966/129173548-0b56a504-5c41-47e8-ab18-941fc95f13b1.png)
![image](https://user-images.githubusercontent.com/10217966/129173799-aedebd8b-b01d-46c4-926e-a13561cfd63f.png)

**Comment by pavel-kirienko** [comment]
I don't see where the conversion is taking place. Which version of Clang-Tidy is this? Libcanard is currently analyzed with Clang Tools version 11.

**Comment by Linjieqiang** [comment]
I use the segger embedded studio ide to analyze the code. The wiki: https://wiki.segger.com/Static_code_analysis_in_Embedded_Studio

**Comment by pavel-kirienko** [comment]
Idk this doesn't make sense to me. Can you see what it takes to fix this warning? Maybe I am missing something.

**Comment by Linjieqiang** [comment]
![image](https://user-images.githubusercontent.com/10217966/129206185-c62532e0-b30b-4b4d-a7da-fda74899db7c.png)

**Comment by Linjieqiang** [comment]
https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-narrowing-conversions.html

**Comment by Linjieqiang** [comment]
`(int8_t)((-(int8_t)(uint8_t) ~val) - 1)` and `((int8_t) val)`

**Comment by Linjieqiang** [comment]
When I remove the `libcanard\.clang-tidy`, the code static check is fine.

**Comment by Linjieqiang** [comment]
Maybe you could use the clang 12 to try CI?

**Comment by thirtytwobits** [comment]
Hmm. I'm not able to reproduce. Can you take a look here:

https://godbolt.org/z/Mdrar3jTo

**Comment by Linjieqiang** [comment]
That is really a strange problem, I think it has nothing to do with IDE. But why this error is reported, I am not sure.

**Comment by Linjieqiang** [comment]
Maybe it was a warning, but the inspection conditions are too strict. @thirtytwobits

**Comment by pavel-kirienko** [comment]
@Linjieqiang it would help if you could isolate the issue to a minimal working example. Also, consider checking the Clang bug tracker to see if this is a known issue. Maybe ask the maintainers about this for good measure unless someone did that already. In the worst case, we may need to add a NOLINT comment on the offending lines to suppress this diagnostic.

**Comment by Linjieqiang** [comment]
Still haven't found the reason, why don't we use NOLINT to circumvent this problem?

**Comment by pavel-kirienko** [comment]
We need an MWE first. Please extract the offending fragment into a separate unit and see if you can reproduce the problem there.

**Comment by Linjieqiang** [comment]
Thanks. @pavel-kirienko

**Comment by pavel-kirienko** [comment]
I didn't really fix it, the code in question was removed from the library (use Nunavut instead).
