### ISSUE TITLE
Porting Example??? 

### ISSUE THREAD

**Issue by karu2003** [UAVCAN/libcanard#40]
Добрый день Павел,

У вас так и не появилось руководство как портировать код на другие платформы?
Какие функции и структуры нужно реализовать? Какую утилиту нужно использовать для преобразования словаря в ".c" и ".h"
Спасибо за совет.

Андрей. 

https://github.com/karu2003/MotorWare_eCAN

**Comment by pavel-kirienko** [comment]
Hello Andrey,

I'm publishing this diagram here in the way of answering your question about porting:

![libuavcan vs libcanard arch](https://cloud.githubusercontent.com/assets/3298404/25637270/161e12d2-2f8d-11e7-8aa3-28114672515f.png)

Observe that Libcanard does not interact with the platform directly; therefore, it does not impose any requirements on the implementation of the platform driver. You can resort to the existing drivers for reference, and you will see that they are all slightly different. This is unlike libuavcan, which does have a well-defined interface between the library and the platform that warrants a dedicated porting guide.

Concerning the code generation issue: Libcanard does not support that, but any help is welcome (see https://github.com/UAVCAN/libcanard/pull/6). You will have to implement serialization and deserialization routines manually, which is not difficult. Please use the demo application as a reference; also see `canardEncodeScalar()` and `canardDecodeScalar()`.

P.S. please speak English here.
