### ISSUE TITLE
Some issues with function "canardRequestOrRespond"

### ISSUE THREAD

**Issue by Linjieqiang** [UAVCAN/libcanard#56]
```
int16_t canardRequestOrRespond(CanardInstance* ins,             ///< Library instance
                               uint8_t destination_node_id,     ///< Node ID of the server/client
                               uint64_t data_type_signature,    ///< See above
                               uint8_t data_type_id,            ///< Refer to the specification
                               uint8_t* inout_transfer_id,      ///< Pointer to a persistent variable with transfer ID
                               uint8_t priority,                ///< Refer to definitions CANARD_TRANSFER_PRIORITY_*
                               CanardRequestResponse kind,      ///< Refer to CanardRequestResponse
                               const void* payload,             ///< Transfer payload
                               uint16_t payload_len);           ///< Length of the above, in bytes
```
Should the "data_type_id" be "uint16_t" not "uint8_t"? 
I met some problems with canard library. 

I want to use "1100.ArmingStatus.uavcan" with "service" so that I can use it with one button to change the FlightController armed status.

**Comment by kjetilkjeka** [comment]
A DSDL definition is **either** a service or a message. If it is a service the request/response part is seperated by `---`. `uavcan.equipment.safety.ArmingStatus` does not contain `---` and can **not** be used as a service.

> Should the "data_type_id" be "uint16_t" not "uint8_t"?

The data type id for service invocations are 8bit and 16bit for message broadcasting. 8 bit is correct in this case as RequestOrRespond refers to a service.

---

I haven't used this message myself, but I assume you can send it periodically or upon change and make the FC listen to this message.
